export const RecentOrders = [
  {
    id: 1,
    image: "../assets/item1.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Pending",
    statuStyle: "pening",
  },
  {
    id: 2,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 3,
    image: "../assets/item1.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Pending",
    statuStyle: "pening",
  },
  {
    id: 4,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 5,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 6,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 7,
    image: "../assets/item1.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Pending",
    statuStyle: "pening",
  },
  {
    id: 8,
    image: "../assets/item1.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Pending",
    statuStyle: "pening",
  },
  {
    id: 9,
    image: "../assets/item1.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Pending",
    statuStyle: "pening",
  },
  {
    id: 10,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 11,
    image: "../assets/item1.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Pending",
    statuStyle: "pening",
  },
  {
    id: 12,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 13,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },

  {
    id: 14,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 15,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
  {
    id: 16,
    image: "../assets/item2.png",
    item: "iPhone 13",
    price: "₦730,000.00",
    quantity: "x 1",
    date: "12 Sept 2022",
    status: "Completed",
    statuStyle: "completed",
  },
];

export const SalesData = [
  {
    id: 1,
    day: "Sept 10",
    sales: 90,
  },
  {
    id: 2,
    day: "Sept 11",
    sales: 40,
  },
  {
    id: 3,
    day: "Sept 12",
    sales: 70,
  },
  {
    id: 4,
    day: "Sept 13",
    sales: 20,
  },
  {
    id: 5,
    day: "Sept 14",
    sales: 80,
  },
  {
    id: 6,
    day: "Sept 15",
    sales: 50,
  },
  {
    id: 7,
    day: "Sept 16",
    sales: 80,
  },
];

export const MarketingData = [];

export const ContactCards = [
  {
    id: 1,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 2,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 3,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 4,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 5,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 6,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 7,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 8,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 9,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 10,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 11,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
  {
    id: 12,
    image: "..assets/profile.svg",
    name: "Jone Deo",
    message: "Hi, i want make enquiries...",
    status: "new",
    time: "12:15 am",
  },
];
